### ISSUE TITLE
join.milliondevs.com [ Set up ] 

### ISSUE THREAD

**Issue by robbiekruszynski** [rapid-eth/rapid-ideas#10]
- [ ] Set up join.milliondevs.com domain

**Comment by robbiekruszynski** [comment]
@KamesCG 
01/28/20 will push/work on this and this ticket can move forward (Tues)

**Comment by joeb000** [comment]
Joe to give Kames credentials on AWS account to allow him to use amplify to setup site

**Comment by robbiekruszynski** [comment]
@orbro I know we set these up yesterday with Firebase.
We good with this ticket?

**Comment by orbro** [comment]
@Robbiekruszynski yessir, move to Done!
